name: Build, Integration, and Testing Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ---------- BUILD ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r Sdn/requirements.txt

  # ---------- INTEGRATION ----------
  integration:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Sdn   # run commands inside repo folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ML Model
        run: python ml_model.py

  # ---------- TESTING ----------
  testing:
    needs: integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Sdn   # run commands inside repo folder
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest -v
